### ISSUE TITLE
[Feature] 建议访问登录url前判断ip地址是否属于CPU网段

### ISSUE THREAD

**Issue by LucienShaw** [Johnshall/CPU-web-login#1]
如题，如果ip地址不在CPU网段，那192.168.199.21将无法访问；又因为苹果快捷指令无法设置超时时间，故该快捷指令将许久无法返回信息。
这将影响使用体验：iphone手机连入CPU时有可能不会立即获得ip地址（CPU的dhcp服务器拥堵，或者因其他情况导致这样的情况，看上去连上了，其实没连上），此时拿到的地址可能是蜂窝移动数据的ip地址或者找不到地址，这时就会出现上述情况。

建议：在获取ip地址这一步设置死循环，获取ip地址后初步判断是否属于10.0.0.0/8网段（可通过字符串截取进行判断），如果不是，则等待一秒再获取一次ip；如果检测到ip地址属于内网（成功获取到了ip），则跳出循环开始登录，否则继续等待；如果多次失败则跳出循环并报错退出。

**Comment by Johnshall** [comment]
OK, I made it.
